version: "3.8"

services:
  wa-automate:
    platform: linux/x86_64
    image: bersuadiserua22/wa-automate:latest
    restart: always
    networks:
      - rabbit_mq
      - redis_network
      - server_load_balancer
    environment:
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - BE_SERVER=http://be-service:4000
      - REDIS_HOST=redis
    volumes:
      - ./session:/app/session

networks:
  rabbit_mq:
    external: true
  redis_network:
    external: true
  server_load_balancer:
    external: true
