version: "3.8"

services:
  rabbitmq:
    platform: linux/x86_64
    image: rabbitmq:3-management-alpine
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
      # - ./docker/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbit_mq

networks:
  rabbit_mq:
    driver: bridge
    name: rabbit_mq
