version: "3.8"

services:
  web-portal:
    platform: linux/x86_64
    image: bersuadiserua22/portal-web:latest
    restart: always
    networks:
      - server_load_balancer
    environment:
      - PORT=4000
      - BACKEND=http://be-service:4000
    depends_on:
      - be-service
    ports:
      - "5000:4000"

  be-service:
    platform: linux/x86_64
    image: bersuadiserua22/be-service:latest
    restart: always
    environment:
      - RABBITMQ_URI=amqp://localhost:5672
    networks:
      - server_load_balancer
      - redis_network
      - rabbit_mq
    depends_on:
      - redis
      - rabbitmq
    ports:
      - "4000:4000"

  redis:
    container_name: redis
    image: redis:6.2.7-bullseye
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - redis_network

  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - redis_network

  rabbitmq:
    platform: linux/x86_64
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq-local"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
      # - ./docker/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbit_mq

networks:
  redis_network:
    driver: bridge
  server_load_balancer:
    external: true
  rabbit_mq:
    driver: bridge
